import { useId, useState } from 'react'
import type { OperacaoRecepcionista, RecepcionistaGestao } from '@/types/gestao'
import { Button } from '@/components/ui/button'
import { X } from 'lucide-react'

interface Props { recepcionista?: RecepcionistaGestao; onSalvar: (op: OperacaoRecepcionista) => void; onCancelar: () => void }
const slug=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
export function FormularioRecepcionista({recepcionista,onSalvar,onCancelar}:Props){
  const id=useId().replace(/[^a-z0-9]/gi,'').toLowerCase(); const [nome,setNome]=useState(recepcionista?.nome??''); const [email,setEmail]=useState(recepcionista?.email??''); const [telefone,setTelefone]=useState(recepcionista?.telefone??'')
  const salvar=()=>{if(!nome.trim()||!email.trim())return; const chave=recepcionista?`recep-${recepcionista.id.slice(0,8)}`:`recep-${slug(nome)||id}`; const dados={chave,nome:nome.trim(),email:email.trim(),telefone:telefone.trim()||undefined,ativo:true}; onSalvar(recepcionista?{tipo:'edicao',recepcionistaExistenteId:recepcionista.id,dadosAtualizados:dados}:{tipo:'inclusao',chave,dadosNovos:dados})}
  return <div className="rounded-xl border bg-white p-4 space-y-4"><div className="flex justify-between"><h3 className="font-semibold">{recepcionista?'Editar recepcionista':'Adicionar recepcionista'}</h3><Button variant="ghost" size="icon-xs" onClick={onCancelar} aria-label="Fechar"><X className="size-4"/></Button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Nome *<input autoFocus value={nome} onChange={e=>setNome(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><label className="text-xs font-medium">E-mail de acesso *<input type="email" value={email} disabled={Boolean(recepcionista)} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm disabled:bg-muted"/></label><label className="text-xs font-medium">Telefone<input type="tel" value={telefone} onChange={e=>setTelefone(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label></div><p className="text-xs text-muted-foreground">A recepcionista terá acesso à agenda da equipe, sem acesso à área administrativa. O e-mail de um acesso já criado permanece o mesmo.</p><div className="flex gap-2"><Button onClick={salvar} disabled={!nome.trim()||!email.trim()}>{recepcionista?'Salvar alteração':'Adicionar recepcionista'}</Button><Button variant="ghost" onClick={onCancelar}>Cancelar</Button></div></div>
}
