import { useEffect, useState } from 'react'
import { AlertTriangle, BriefcaseBusiness, CheckCircle2, ChevronLeft, ChevronRight, Plus, Send, UserRoundCog, Users, X } from 'lucide-react'
import { useAuth } from '@/hooks/use-auth'
import { consultarEmpresaGestao } from '@/services/gestao'
import { calcularOcupacao, gerarJsonSolicitacao, validarRascunho } from '@/services/solicitacao-gestao'
import { enviarSolicitacaoGestao } from '@/services/gestao-webhook'
import type { EmpresaGestao, OperacaoProfissional, OperacaoRecepcionista, OperacaoServico, ProfissionalGestao, RecepcionistaGestao, RascunhoGestao, ServicoGestao } from '@/types/gestao'
import { LoadingState, ErrorState, UnauthorizedState } from '@/components/ui/state'
import { Button } from '@/components/ui/button'
import { ProfissionalCard } from '@/components/gestao/profissional-card'
import { RecepcionistaCard } from '@/components/gestao/recepcionista-card'
import { ServicoCard } from '@/components/gestao/servico-card'
import { FormularioProfissional } from '@/components/gestao/formulario-profissional'
import { FormularioRecepcionista } from '@/components/gestao/formulario-recepcionista'
import { FormularioServico } from '@/components/gestao/formulario-servico'
import { ResumoSolicitacao } from '@/components/gestao/resumo-solicitacao'

type Etapa='pessoas'|'servicos'|'revisao'
const vazio=():RascunhoGestao=>({operacoesProfissionais:[],operacoesRecepcionistas:[],operacoesServicos:[],criadoEm:new Date().toISOString()})
function substituir<T>(lista:T[],op:T,id:(x:T)=>string|undefined){const chave=id(op);return chave?[...lista.filter(x=>id(x)!==chave),op]:[...lista,op]}

export function GestaoPage(){
 const {usuario,isAdmin,empresa}=useAuth(); const [dados,setDados]=useState<EmpresaGestao|null>(null); const [loading,setLoading]=useState(true); const [erro,setErro]=useState(''); const [editando,setEditando]=useState(false); const [etapa,setEtapa]=useState<Etapa>('pessoas'); const [rascunho,setRascunho]=useState<RascunhoGestao|null>(null); const [form,setForm]=useState<'profissional'|'recepcionista'|'servico'|null>(null); const [alvo,setAlvo]=useState<ProfissionalGestao|RecepcionistaGestao|ServicoGestao|null>(null); const [enviando,setEnviando]=useState(false); const [mensagem,setMensagem]=useState<{tipo:'sucesso'|'erro';texto:string}|null>(null)
 useEffect(()=>{if(!usuario?.empresaId)return; void consultarEmpresaGestao(usuario.empresaId).then(r=>{if(r.sucesso&&r.dados)setDados(r.dados);else setErro(r.erro??'Erro ao carregar dados.');setLoading(false)})},[usuario?.empresaId])
 if(!isAdmin)return <UnauthorizedState/>; if(loading)return <LoadingState message="Carregando gestão..."/>; if(erro)return <ErrorState title="Erro ao carregar" description={erro}/>; if(!dados)return <ErrorState title="Empresa não encontrada"/>
 const ocupacao=calcularOcupacao(dados,rascunho); const total=(rascunho?.operacoesProfissionais.length??0)+(rascunho?.operacoesRecepcionistas.length??0)+(rascunho?.operacoesServicos.length??0)
 const iniciar=()=>{setRascunho(vazio());setEditando(true);setEtapa('pessoas');setMensagem(null)}; const cancelar=()=>{setRascunho(null);setEditando(false);setForm(null);setAlvo(null);setEtapa('pessoas')}; const abrir=(tipo:typeof form,item:typeof alvo=null)=>{setAlvo(item);setForm(tipo)}
 const salvarProf=(op:OperacaoProfissional)=>setRascunho(r=>r?{...r,operacoesProfissionais:substituir(r.operacoesProfissionais,op,x=>x.profissionalExistenteId)}:r)
 const salvarRec=(op:OperacaoRecepcionista)=>setRascunho(r=>r?{...r,operacoesRecepcionistas:substituir(r.operacoesRecepcionistas,op,x=>x.recepcionistaExistenteId)}:r)
 const salvarSrv=(op:OperacaoServico)=>setRascunho(r=>r?{...r,operacoesServicos:substituir(r.operacoesServicos,op,x=>x.servicoExistenteId)}:r)
 const fecharForm=()=>{setForm(null);setAlvo(null)}
 const enviar=async()=>{if(!rascunho)return;const v=validarRascunho(dados,rascunho);if(!v.valido){setMensagem({tipo:'erro',texto:v.erros.join(' ')});return}setEnviando(true);const solicitacao=gerarJsonSolicitacao(dados,rascunho,rascunho.solicitacaoId);setRascunho({...rascunho,solicitacaoId:solicitacao.solicitacao_id});const r=await enviarSolicitacaoGestao({solicitacao});setEnviando(false);if(r.sucesso){setMensagem({tipo:'sucesso',texto:'Alterações aplicadas com sucesso.'});cancelar();const atual=await consultarEmpresaGestao(usuario!.empresaId);if(atual.dados)setDados(atual.dados)}else setMensagem({tipo:'erro',texto:r.mensagem})}
 const desfazer=(tipo:'p'|'r'|'s',i:number)=>setRascunho(r=>!r?r:{...r,operacoesProfissionais:tipo==='p'?r.operacoesProfissionais.filter((_,n)=>n!==i):r.operacoesProfissionais,operacoesRecepcionistas:tipo==='r'?r.operacoesRecepcionistas.filter((_,n)=>n!==i):r.operacoesRecepcionistas,operacoesServicos:tipo==='s'?r.operacoesServicos.filter((_,n)=>n!==i):r.operacoesServicos})
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Equipe e serviços</h2><p className="text-sm text-muted-foreground">{dados.nomeFantasia??empresa?.nome}</p></div>{!editando?<Button onClick={iniciar}><UserRoundCog className="size-4"/>Entrar no modo de edição</Button>:<Button variant="ghost" onClick={cancelar}><X className="size-4"/>Descartar alterações</Button>}</div>
  {mensagem&&<div className={`flex gap-2 rounded-lg border p-3 text-sm ${mensagem.tipo==='sucesso'?'bg-success-50 text-success-600':'bg-danger-50 text-danger-600'}`}>{mensagem.tipo==='sucesso'?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}{mensagem.texto}</div>}
  {editando&&<><div className="grid grid-cols-3 gap-2">{([['pessoas','1','Pessoas'],['servicos','2','Serviços'],['revisao','3','Revisão']] as const).map(([k,n,t])=><button key={k} onClick={()=>setEtapa(k)} className={`rounded-xl border p-3 text-left ${etapa===k?'border-primary-600 bg-primary-50':'bg-white'}`}><span className="text-xs text-muted-foreground">Etapa {n}</span><p className="text-sm font-semibold">{t}</p></button>)}</div><div className="rounded-xl border bg-primary-50/40 p-3 text-sm">Você está preparando alterações. O banco só será atualizado quando confirmar na última etapa. {total>0&&<strong className="ml-1">{total} alteração(ões) pendente(s).</strong>}</div></>}
  {form==='profissional'&&<FormularioProfissional empresa={dados} rascunho={rascunho} profissional={alvo as ProfissionalGestao||undefined} onSalvar={o=>{salvarProf(o);fecharForm()}} onCancelar={fecharForm}/>} {form==='recepcionista'&&<FormularioRecepcionista recepcionista={alvo as RecepcionistaGestao||undefined} onSalvar={o=>{salvarRec(o);fecharForm()}} onCancelar={fecharForm}/>} {form==='servico'&&<FormularioServico servico={alvo as ServicoGestao||undefined} onSalvar={o=>{salvarSrv(o);fecharForm()}} onCancelar={fecharForm}/>}
  {(!editando||etapa==='pessoas')&&<div className="space-y-5"><section className="space-y-3"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Users className="size-4"/>Profissionais <span className="text-xs font-normal text-muted-foreground">{ocupacao.proposta}/{ocupacao.capacidade}</span></h3>{editando&&<Button size="sm" variant="outline" onClick={()=>abrir('profissional')} disabled={ocupacao.vagasDisponiveis===0}><Plus className="size-4"/>Adicionar</Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dados.profissionais.filter(p=>p.ativo).map(p=><ProfissionalCard key={p.id} profissional={p} servicos={dados.servicos} modoRascunho={editando} rascunho={rascunho} onEditar={()=>abrir('profissional',p)} onRemover={id=>salvarProf({tipo:'remocao',profissionalExistenteId:id})} onDesfazerRemocao={i=>desfazer('p',i)}/>)}</div></section>
  <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><UserRoundCog className="size-4"/>Recepcionistas <span className="text-xs font-normal text-muted-foreground">{ocupacao.recepcionistasPropostos}/{ocupacao.capacidadeRecepcionistas}</span></h3>{editando&&<Button size="sm" variant="outline" onClick={()=>abrir('recepcionista')} disabled={ocupacao.recepcionistasPropostos>=ocupacao.capacidadeRecepcionistas}><Plus className="size-4"/>Adicionar</Button>}</div>{dados.recepcionistas.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dados.recepcionistas.filter(r=>r.ativo).map(r=><RecepcionistaCard key={r.id} recepcionista={r} rascunho={rascunho} editando={editando} onEditar={()=>abrir('recepcionista',r)} onRemover={()=>salvarRec({tipo:'remocao',recepcionistaExistenteId:r.id})} onDesfazer={i=>desfazer('r',i)}/>)}</div>:<p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">Nenhuma recepcionista cadastrada.</p>}</section></div>}
  {(!editando||etapa==='servicos')&&<section className="space-y-3"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><BriefcaseBusiness className="size-4"/>Serviços</h3>{editando&&<Button size="sm" variant="outline" onClick={()=>abrir('servico')}><Plus className="size-4"/>Adicionar</Button>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dados.servicos.filter(s=>s.ativo).map(s=><ServicoCard key={s.id} servico={s} profissionais={dados.profissionais} modoRascunho={editando} rascunho={rascunho} onEditar={()=>abrir('servico',s)} onRemover={id=>salvarSrv({tipo:'remocao',servicoExistenteId:id})} onDesfazer={i=>desfazer('s',i)}/>)}</div></section>}
  {editando&&etapa==='revisao'&&rascunho&&<ResumoSolicitacao empresa={dados} rascunho={rascunho} ocupacao={ocupacao} onEnviar={enviar} onVoltar={()=>setEtapa('servicos')} enviando={enviando}/>}
  {editando&&etapa!=='revisao'&&<div className="sticky bottom-3 flex justify-between rounded-xl border bg-white/95 p-3 shadow-lg backdrop-blur"><Button variant="ghost" onClick={()=>setEtapa(etapa==='servicos'?'pessoas':'pessoas')} disabled={etapa==='pessoas'}><ChevronLeft className="size-4"/>Voltar</Button><Button onClick={()=>setEtapa(etapa==='pessoas'?'servicos':'revisao')} disabled={form!==null}>{etapa==='servicos'?<><Send className="size-4"/>Revisar</>:<>Continuar<ChevronRight className="size-4"/></>}</Button></div>}
 </div>
}
